[package]
name = "bully"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "0.5.12"
crossbeam = "0.8.4"
clap = { version = "4.5.2", features = ["derive"] }
tdigest = "0.1.1"
